/**
 * The ESLint config the gate uses in `kit` mode: the project's own config (if
 * any) with the kit preset and the ruleset's extra rules on top. It is
 * generated on every run in the state folder (inside `.git`), so the repo does
 * not change.
 */

import { existsSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { pathToFileURL } from 'node:url';

import { slug } from '../config.mjs';
import { ensureDir } from '../project.mjs';
import { listFiles } from '../git/git.mjs';
import { depsRoot, KIT_ROOT, loadDep, MissingDepsError } from '../runtime.mjs';

const CONFIG_NAMES = ['eslint.config.js', 'eslint.config.mjs', 'eslint.config.cjs'];
export const DEFAULT_IGNORES = ['**/node_modules/**', '**/dist/**', '**/build/**', '**/.next/**', '**/out/**', '**/coverage/**', '**/*.d.ts', '**/_generated/**'];

/** The project's flat config for the workspace: its own or the root one. */
export function findProjectConfig(repo, workspaceDir, exists = existsSync) {
  const dirs = [...new Set([join(repo, workspaceDir), repo])];
  for (const dir of dirs) {
    const found = CONFIG_NAMES.map((name) => join(dir, name)).find(exists);
    if (found) return found;
  }
  return null;
}

/** The config module source. Pure, so it can be tested without ESLint. */
export function overlaySource({ deps, presetPath, projectConfig, extraRules, tsconfigRootDir, tsconfigs = [], untyped = [], ignores }) {
  const json = JSON.stringify;
  const projectLine = projectConfig
    ? `[(await import(${json(pathToFileURL(projectConfig).href)})).default].flat(Infinity)`
    : `[js.configs.recommended, ...tseslint.configs.recommended, { languageOptions: { globals: { ...globals.browser, ...globals.node } } }]`;
  const extraLine = extraRules ? `kitRequire(${json(extraRules)})` : '{}';
  return `// Generated by quality-kit on every gate run. Do not edit: the ruleset lives in the project folder in the kit.
import { createRequire } from 'node:module';

const kitRequire = createRequire(${json(join(deps, 'package.json'))});
const { buildQuality, warningsAsErrors } = kitRequire(${json(presetPath)});
const js = kitRequire('@eslint/js');
const tseslint = kitRequire('typescript-eslint');
const globals = kitRequire('globals');
const sonarjs = kitRequire('eslint-plugin-sonarjs');
const comments = kitRequire('@eslint-community/eslint-plugin-eslint-comments');

const project = ${projectLine};
const extra = ${extraLine};
const registered = (name) => project.find((config) => config?.plugins?.[name])?.plugins[name];
const parser = project.find((config) => config?.languageOptions?.parser)?.languageOptions.parser ?? tseslint.parser;

export default warningsAsErrors([
  { ignores: ${json(ignores)} },
  ...project,
  { files: ['**/*.jsx'], languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } } },
  ...buildQuality({
    plugins: {
      sonarjs: registered('sonarjs') ?? sonarjs,
      comments: registered('@eslint-community/eslint-comments') ?? comments,
      typescript: registered('@typescript-eslint') ?? tseslint.plugin,
      parser,
    },
    tsconfigRootDir: ${json(tsconfigRootDir)},
    tsconfigs: ${json(tsconfigs)},
    untyped: ${json(untyped)},
    restrictedSyntax: extra.restrictedSyntax ?? [],
  }),
  ...[extra.configs ?? []].flat(Infinity),
]);
`;
}

/**
 * The ruleset flags (`--strict`, `--noUncheckedIndexedAccess`) as
 * compilerOptions. A flag followed by a value (`--target es2022`) takes it.
 */
export function flagsToOptions(flags) {
  const options = {};
  for (let index = 0; index < flags.length; index += 1) {
    const name = flags[index].replace(/^--/, '');
    const next = flags[index + 1];
    const hasValue = next !== undefined && !next.startsWith('--');
    options[name] = hasValue ? next : true;
    if (hasValue) index += 1;
  }
  return options;
}

/**
 * One tsconfig per workspace tsconfig, extending the project's and enabling
 * the strict flags: type-aware lint sees the same strict program as tsc,
 * without touching the repo tsconfig. It lives in the state folder, inside `.git`.
 */
export function writeStrictTsconfigs({ project, config, workspace }) {
  const dir = ensureDir(join(project.stateDir, 'tsconfig'));
  return [workspace.tsconfig]
    .flat()
    .filter(Boolean)
    .map((tsconfig) => {
      const file = join(dir, `${slug(workspace.dir)}--${tsconfig.replace(/[/\\]/g, '__')}`);
      const content = { extends: join(project.repo, workspace.dir, tsconfig), compilerOptions: flagsToOptions(config.typescript.flags) };
      writeFileSync(file, `${JSON.stringify(content, null, 2)}\n`);
      return file;
    });
}

/**
 * The workspace TS files no tsconfig includes (tool config, standalone
 * scripts): without a program, type-aware lint cannot run on them, so they
 * only get the untyped rules.
 */
export function untypedFiles(workspaceFiles, covered) {
  return workspaceFiles.filter((file) => /\.[cm]?tsx?$/.test(file) && !file.endsWith('.d.ts') && !covered.has(file));
}

function coveredFiles(tsconfigs, root) {
  const ts = loadDep('typescript');
  const host = { ...ts.sys, onUnRecoverableConfigFileDiagnostic: () => undefined };
  const covered = new Set();
  for (const tsconfig of tsconfigs) {
    for (const file of ts.getParsedCommandLineOfConfigFile(tsconfig, {}, host)?.fileNames ?? []) covered.add(relative(root, file).split('\\').join('/'));
  }
  return covered;
}

/** Writes the workspace config and returns its path. */
export function writeOverlay({ project, config, workspace }) {
  const deps = depsRoot();
  if (!deps) throw new MissingDepsError();
  const extraPath = join(project.rulesDir, config.lint.extraRules);
  const root = join(project.repo, workspace.dir);
  const tsconfigs = writeStrictTsconfigs({ project, config, workspace });
  const workspaceFiles = listFiles(project.repo).filter((file) => file.startsWith(workspace.dir)).map((file) => file.slice(workspace.dir.length));
  const source = overlaySource({
    deps,
    presetPath: join(KIT_ROOT, 'src', 'lint', 'preset.cjs'),
    projectConfig: config.lint.projectConfig === false ? null : findProjectConfig(project.repo, workspace.dir),
    extraRules: existsSync(extraPath) ? extraPath : null,
    tsconfigRootDir: root,
    tsconfigs,
    untyped: tsconfigs.length > 0 ? untypedFiles(workspaceFiles, coveredFiles(tsconfigs, root)) : [],
    ignores: [...DEFAULT_IGNORES, ...(config.lint.ignores ?? [])],
  });
  const file = join(ensureDir(join(project.stateDir, 'eslint')), `${slug(workspace.dir)}.config.mjs`);
  writeFileSync(file, source);
  return file;
}
