// The strict quality-kit preset: what project instructions ask for in prose
// becomes a lint error. Everything is "error" (a warning blocks nothing and
// just piles up). The debt from when the ruleset was adopted stays frozen in
// the baseline, which only shrinks.
//
// Extracted from Flock (eslint.quality.js), without the rules that only apply
// there. A project's own rules come in through `lint-extra.cjs` in the ruleset folder.

const DESIGN_RULES = {
  "max-lines": ["error", { max: 300, skipBlankLines: true, skipComments: true }],
  "max-lines-per-function": ["error", { max: 80, skipBlankLines: true, skipComments: true }],
  complexity: ["error", 15],
  "max-depth": ["error", 3],
  "max-params": ["error", 4],
  "max-nested-callbacks": ["error", 3],
  "no-nested-ternary": "error",
  "no-console": ["error", { allow: ["warn", "error"] }],
};

// Smells agents tend to leave behind: duplicated branches, copied functions,
// swallowed errors, variables written and never read, repeated literals.
const SONAR_RULES = {
  "sonarjs/cognitive-complexity": ["error", 15],
  "sonarjs/no-identical-functions": "error",
  "sonarjs/no-duplicate-string": ["error", { threshold: 3 }],
  "sonarjs/no-all-duplicated-branches": "error",
  "sonarjs/no-duplicated-branches": "error",
  "sonarjs/no-identical-conditions": "error",
  "sonarjs/no-identical-expressions": "error",
  "sonarjs/no-element-overwrite": "error",
  "sonarjs/no-gratuitous-expressions": "error",
  "sonarjs/no-collapsible-if": "error",
  "sonarjs/no-redundant-jump": "error",
  "sonarjs/no-redundant-boolean": "error",
  "sonarjs/no-inverted-boolean-check": "error",
  "sonarjs/prefer-single-boolean-return": "error",
  "sonarjs/no-useless-catch": "error",
  "sonarjs/no-ignored-exceptions": "error",
  "sonarjs/no-dead-store": "error",
  "sonarjs/no-unused-collection": "error",
};

// Well-known hacks: forcing order with setTimeout 0, winning specificity with
// important, switching off the type system with `as unknown as`.
const RESTRICTED_SYNTAX = [
  ...[
    "CallExpression[callee.name='setTimeout'][arguments.length=1]",
    "CallExpression[callee.name='setTimeout'][arguments.1.value=0]",
    "CallExpression[callee.property.name='setTimeout'][arguments.1.value=0]",
  ].map((selector) => ({ selector, message: "setTimeout with a 0 delay is a hack: resolve the ordering with the platform's official mechanism." })),
  ...["JSXAttribute[name.name='className'] Literal[value=/(^|\\s)![\\w\\[-]|[\\w\\]]!(\\s|$)/]", "Literal[value=/!\\s*important/]"].map((selector) => ({
    selector,
    message: "Forcing style priority (important) is a hack: fix the specificity at the source.",
  })),
  { selector: "TSAsExpression > TSAsExpression[typeAnnotation.type='TSUnknownKeyword']", message: "`as unknown as` switches off the type: fix the type at the source." },
];

// With type information: `any`, forgotten promises, guards for what the type
// already guarantees, no-op casts, switches missing a case, deprecated APIs.
const TYPESCRIPT_RULES = {
  "@typescript-eslint/no-explicit-any": "error",
  "@typescript-eslint/no-non-null-assertion": "error",
  "@typescript-eslint/ban-ts-comment": "error",
  "@typescript-eslint/no-unused-vars": "error",
  "@typescript-eslint/no-floating-promises": "error",
  "@typescript-eslint/no-misused-promises": "error",
  "@typescript-eslint/await-thenable": "error",
  "@typescript-eslint/no-unnecessary-condition": "error",
  "@typescript-eslint/no-unnecessary-type-assertion": "error",
  "@typescript-eslint/switch-exhaustiveness-check": "error",
  "@typescript-eslint/no-deprecated": "error",
  "@typescript-eslint/no-unsafe-argument": "error",
  "@typescript-eslint/no-unsafe-assignment": "error",
  "@typescript-eslint/no-unsafe-call": "error",
  "@typescript-eslint/no-unsafe-member-access": "error",
  "@typescript-eslint/no-unsafe-return": "error",
};

// Quality rules cannot be disabled by comment: the comment is exactly the
// escape hatch an agent would use to avoid refactoring.
const LOCKED_RULES = [
  ...Object.keys(DESIGN_RULES),
  ...Object.keys(SONAR_RULES),
  ...Object.keys(TYPESCRIPT_RULES),
  "no-restricted-syntax",
  "no-restricted-imports",
  "react-hooks/*",
  "@eslint-community/eslint-comments/*",
];

const TESTS = ["**/*.test.*", "**/*.spec.*", "**/__tests__/**", "**/__mocks__/**", "e2e/**", "**/testing/**"];
const NODE_SCRIPTS = ["scripts/**", "**/*.config.{js,cjs,mjs,ts,mts,cts}"];
const TYPESCRIPT = ["**/*.{ts,tsx,mts,cts}"];

/**
 * The preset as a list of flat configs. `plugins` lets it reuse the instance
 * the project already registered (ESLint rejects the same name bound to two
 * different objects).
 */
function buildQuality({ plugins, tsconfigRootDir, tsconfigs = [], untyped = [], restrictedSyntax = [] }) {
  // With the strict tsconfigs generated by the kit, lint sees the same types as
  // the typecheck; without a tsconfig, the project service finds the nearest one.
  const parserOptions = tsconfigs.length > 0 ? { project: tsconfigs, tsconfigRootDir } : { projectService: true, tsconfigRootDir };
  const syntax = ["error", ...RESTRICTED_SYNTAX, ...restrictedSyntax];
  return [
    { linterOptions: { reportUnusedDisableDirectives: "error", reportUnusedInlineConfigs: "error" } },
    {
      plugins: { sonarjs: plugins.sonarjs, "@eslint-community/eslint-comments": plugins.comments },
      rules: {
        ...DESIGN_RULES,
        ...SONAR_RULES,
        "no-restricted-syntax": syntax,
        "@eslint-community/eslint-comments/no-restricted-disable": ["error", ...LOCKED_RULES],
        "@eslint-community/eslint-comments/no-use": ["error", { allow: ["eslint-disable-next-line"] }],
        "@eslint-community/eslint-comments/require-description": "error",
        "@eslint-community/eslint-comments/no-unlimited-disable": "error",
        "@eslint-community/eslint-comments/no-aggregating-enable": "error",
        "@eslint-community/eslint-comments/no-duplicate-disable": "error",
        "@eslint-community/eslint-comments/no-unused-enable": "error",
      },
    },
    {
      files: TYPESCRIPT,
      ignores: untyped,
      plugins: { "@typescript-eslint": plugins.typescript },
      languageOptions: { parser: plugins.parser, parserOptions },
      rules: TYPESCRIPT_RULES,
    },
    {
      // Tests are long by nature and use `!` and setTimeout to wait and assert.
      files: TESTS,
      rules: {
        "max-lines": "off",
        "max-lines-per-function": "off",
        "max-nested-callbacks": "off",
        "no-console": "off",
        "no-restricted-syntax": "off",
        "sonarjs/no-duplicate-string": "off",
        "sonarjs/no-identical-functions": "off",
        "@typescript-eslint/no-non-null-assertion": "off",
      },
    },
    { files: NODE_SCRIPTS, rules: { "no-console": "off" } },
  ];
}

function asError(entry) {
  if (entry === "warn" || entry === 1) return "error";
  if (Array.isArray(entry) && (entry[0] === "warn" || entry[0] === 1)) return ["error", ...entry.slice(1)];
  return entry;
}

/**
 * Lint runs with --max-warnings 0 and only "error" fits in the suppressions
 * file: warnings from the project preset become errors, so their debt is
 * frozen too instead of blocking everything.
 */
function warningsAsErrors(configs) {
  return configs.map((config) =>
    config.rules ? { ...config, rules: Object.fromEntries(Object.entries(config.rules).map(([rule, entry]) => [rule, asError(entry)])) } : config,
  );
}

module.exports = { buildQuality, warningsAsErrors, LOCKED_RULES, TYPESCRIPT_RULES, DESIGN_RULES };
